### ISSUE TITLE
welcome page completed with buttons

### ISSUE THREAD

**Issue by ahammer1** [NSS-Evening-E22/pos-system-tech-giants#4]
As a user, I want to be greeted with a welcome page that provides an introduction to the website and its purpose.

Acceptance Criteria:

The welcome page should be visually appealing and engaging to the user.
The welcome page should provide a brief overview of the website's purpose and features.
The welcome page should include links to important sections of the website.
The welcome page should include a call to action that encourages the user to register or login.
Dependencies:

The website's purpose, features, and page structure should be established.
The front-end web development framework or library should be selected.
Dev Notes:

Design a visually appealing and engaging welcome page.
Write compelling copy that provides a brief overview of the website's purpose and features.
Include links to important sections of the website on the welcome page.
Create a call to action that encourages the user to register or login.
Implement the welcome page in HTML, CSS, and JavaScript.
Test the welcome page thoroughly to ensure that it is engaging, functional, and effective in introducing the website to new users.

**Comment by dimitricbrown** [comment]
Create Order and View Revenue Button issues have been created.
